apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.serviceName }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: "b2b-platform-{{ .Values.namespace }}"
    {{- if .Values.wafWebAclArn }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.wafWebAclArn | quote }}
    {{- end }}
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /{{ .Values.serviceName }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.serviceName }}-svc
                port:
                  number: 80
